stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/7incho/concesionario-backend

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker tag $IMAGE_NAME:$CI_COMMIT_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - tags

update-infra:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "gitlab-ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git clone https://oauth2:${INFRA_TOKEN}@gitlab.com/7incho/infra-asistencia.git
    - cd infra-asistencia
    - "sed -i \"s|image: registry.gitlab.com/7incho/concesionario-backend:.*|image: registry.gitlab.com/7incho/concesionario-backend:${CI_COMMIT_TAG}|g\" apps/backend/deployment.yaml"
    - git add apps/backend/deployment.yaml
    - "git commit -m \"Update concesionario-backend to version ${CI_COMMIT_TAG}\""
    - git push origin main
  only:
    - tags
